# Generated by Django 6.0.5 on 2026-07-09 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('github_repo', models.CharField(blank=True, help_text='Format: owner/repo (e.g. PuneethKrishnaS/SoftMade)', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUIREMENT', 'Requirement Collection'), ('TOPIC', 'Topic Finalization'), ('SYNOPSIS', 'Synopsis Preparation'), ('DESIGN', 'UI/UX Design'), ('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend Development'), ('DATABASE', 'Database Integration'), ('TESTING', 'Testing Phase'), ('REPORT', 'Report Preparation'), ('DEPLOYMENT', 'Deployment'), ('DELIVERED', 'Final Delivery')], default='REQUIREMENT', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='students.student')),
                ('students', models.ManyToManyField(blank=True, related_name='projects', to='students.student')),
            ],
        ),
    ]
